spring.application.name=smart-mess-management
spring.datasource.url=jdbc:mysql://localhost:3306/smart_mess_db
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080